image: maven

stages:
  - build
  - deploy

buildJob:
  stage: build
  script:
  - mvn install -DskipTests -s prerequisites/.m2/settings.xml -Dsettings.security=prerequisites/.m2/settings-security.xml
  
deployJob:
  stage: deploy
  script: 
  - mvn deploy -DskipTests -s prerequisites/.m2/settings.xml -Dsettings.security=prerequisites/.m2/settings-security.xml
  