image: maven

stages:
   - test
   - build
   - deploy
   
testJob:
   services:
   - andreptb/jboss-as:5.1.0.GA
   stage: test
   script:
   - ls -l /opt
   - mvn test -s prerequisites/.m2/settings.xml -Dsettings.security=prerequisites/.m2/settings-security.xml
  
buildJob:
  stage: build
  script:
  - mvn install -DskipTests -s prerequisites/.m2/settings.xml -Dsettings.security=prerequisites/.m2/settings-security.xml
  
deployJob:
  stage: deploy
  script: 
  - mvn deploy -DskipTests -Pskinny-war -s prerequisites/.m2/settings.xml -Dsettings.security=prerequisites/.m2/settings-security.xml
  

