image: maven

stages:
   - test
   - build
   - deploy
   
testJob:
   image: jboss/base
   stage: test
   script:
   - mvn test -s prerequisites/.m2/settings.xml -Dsettings.security=prerequisites/.m2/settings-security.xml
  
buildJob:
  stage: build
  script:
  - mvn install -DskipTests -s prerequisites/.m2/settings.xml -Dsettings.security=prerequisites/.m2/settings-security.xml
  
deployJob:
  stage: deploy
  script: 
  - mvn deploy -DskipTests -Pskinny-war -s prerequisites/.m2/settings.xml -Dsettings.security=prerequisites/.m2/settings-security.xml
  

